### ISSUE TITLE
flax.errors.InvalidRngError: rngs should be a dictionary mapping strings to `jax.PRNGKey`

### ISSUE THREAD

**Issue by Cascol-SCUT** [google-research/vmoe#2]
#### Error log
```c
Traceback (most recent call last):
  File "vmoe/main.py", line 71, in <module>
    app.run(main)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "vmoe/main.py", line 64, in main
    trainer.train_and_evaluate(config=FLAGS.config, workdir=FLAGS.workdir)
  File "/mnt/cephfs/home/cascol/working-directory/MoE-in-MoE/vmoe/vmoe/train/trainer.py", line 434, in train_and_evaluate
    tree=jax.eval_shape(train_state_initialize_fn, train_state_rngs),
  File "/mnt/cephfs/home/cascol/working-directory/MoE-in-MoE/vmoe/vmoe/train/trainer.py", line 203, in initialize
    variables = model.init(rngs, inputs)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/flax/linen/module.py", line 1124, in init
    method=method, mutable=mutable, **kwargs)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/flax/linen/module.py", line 1092, in init_with_output
    {}, *args, rngs=rngs, method=method, mutable=mutable, **kwargs)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 165, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/flax/linen/module.py", line 1061, in apply
    )(variables, *args, **kwargs, rngs=rngs)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/flax/core/scope.py", line 706, in wrapper
    with bind(variables, rngs=rngs, mutable=mutable).temporary() as root:
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe/lib/python3.7/site-packages/flax/core/scope.py", line 684, in bind
    'rngs should be a dictionary mapping strings to `jax.PRNGKey`.')
jax._src.traceback_util.UnfilteredStackTrace: flax.errors.InvalidRngError: rngs should be a dictionary mapping strings to `jax.PRNGKey`. (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.InvalidRngError)
```

#### My Enviroment that may concern
```c
cudatoolkit               11.1.1               h6406543_8    conda-forge
flax                      0.3.6                    pypi_0    pypi
jax                       0.2.27                   pypi_0    pypi
jaxlib                    0.1.75+cuda11.cudnn805          pypi_0    pypi
optax                     0.1.0                    pypi_0    pypi
pytorch                   1.8.0           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
```

### I tried tracking the error and found weird bug (the image on top is the result while setting up training, the image at the bottom is what I think the result should look like)
![微信图片_20220119210347](https://user-images.githubusercontent.com/51443787/150136152-714eee91-f22d-46f5-89f6-63d463bf3c56.png)

![image](https://user-images.githubusercontent.com/51443787/150137046-96eab10e-6914-425b-aeb0-a0c188301122.png)

**Comment by jpuigcerver** [comment]
We use a few experimental features from Jax/Flax which are not yet part of any official release. Upgrade the following packages from GitHub:
```
pip install -q --upgrade git+https://github.com/google/jax.git;
pip install -q --upgrade git+https://github.com/google/flax.git;
pip install -q --upgrade git+https://github.com/google/CommonLoopUtils.git;
```

**Comment by Cascol-SCUT** [comment]
Where should I set up *jax_config.jax_enable_custom_prng=True* to use these experimental features?

> We use a few experimental features from Jax/Flax which are not yet part of any official release. Upgrade the following packages from GitHub:
> 
> ```
> pip install -q --upgrade git+https://github.com/google/jax.git;
> pip install -q --upgrade git+https://github.com/google/flax.git;
> pip install -q --upgrade git+https://github.com/google/CommonLoopUtils.git;
> ```

**Comment by jpuigcerver** [comment]
You shouldn't set `jax_enable_custom_prng`. We use `jax_default_prng_impl`. 

https://github.com/google-research/vmoe/blob/bff362c6abfaf6c518f01e09ea0c6a7b21b8c415/vmoe/main.py#L46

The problem is that the current release of FLAX doesn't work well with this, that's why you need to install FLAX from github. I fixed it less than a week ago: https://github.com/google/flax/commit/4d6400cc2e378d9cacf2702629c3b57b70661053

If it's of any help, this is how I installed all the requirements to try training a model on a GCE instance: https://github.com/google-research/vmoe/blob/main/vmoe/scripts/install_gce.sh

**Comment by Cascol-SCUT** [comment]
Hi, thanks for your patience.
Following your instruction I install all requirements as follows
```c
# install cudatoolkit11 cudnn8.0.5
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge --yes

pip install --upgrade jax[cuda11_cudnn805] -f https://storage.googleapis.com/jax-releases/jax_releases.html

pip install --upgrade git+https://github.com/google/jax.git
pip install --upgrade git+https://github.com/google/flax.git
pip install --upgrade git+https://github.com/google/CommonLoopUtils.git

pip install absl-py cachetools chex einops ml_collections numpy optax pandas scipy tensorflow-cpu tfds-nightly
```
However, another bug occurs when I tried to run cifar10 example on GPU, namely **UNIMPLEMENTED: Requested AllToAll not implemented on GPU**
Here is the error log
```c
2022-01-20 16:40:23.258557: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc:4584] Disabling cuDNN frontend for the following convolution:
  input: {count: 128 feature_map_count: 3 spatial: 128 128  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 768 input_feature_map_count: 3 layout: OutputInputYX shape: 16 16 }
  {zero_padding: 0 0  pad_alignment: default filter_strides: 16 16  dilation_rates: 1 1 }
  ... because the current cuDNN version does not support it.
2022-01-20 16:40:24.573497: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc:4584] Disabling cuDNN frontend for the following convolution:
  input: {count: 128 feature_map_count: 3 spatial: 128 128  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 768 input_feature_map_count: 3 layout: OutputInputYX shape: 16 16 }
  {zero_padding: 0 0  pad_alignment: default filter_strides: 16 16  dilation_rates: 1 1 }
  ... because the current cuDNN version does not support it.
Traceback (most recent call last):
  File "vmoe/main.py", line 71, in <module>
    app.run(main)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe_new/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe_new/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "vmoe/main.py", line 64, in main
    trainer.train_and_evaluate(config=FLAGS.config, workdir=FLAGS.workdir)
  File "/mnt/cephfs/home/cascol/working-directory/MoE-in-MoE/vmoe/vmoe/train/trainer.py", line 492, in train_and_evaluate
    datasets['train'].element_spec['labels']))).compile()
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe_new/lib/python3.7/site-packages/jax/_src/api.py", line 521, in compile
    self._lowering.compile(), self.in_tree, self.out_tree,
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe_new/lib/python3.7/site-packages/jax/interpreters/pxla.py", line 2056, in compile
    _allow_compile_replicated=_allow_compile_replicated)  # type: ignore
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe_new/lib/python3.7/site-packages/jax/interpreters/pxla.py", line 2142, in from_hlo
    compiled = dispatch.compile_or_get_cached(backend, computation, compile_options)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe_new/lib/python3.7/site-packages/jax/_src/dispatch.py", line 582, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe_new/lib/python3.7/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/mnt/cephfs/home/cascol/anaconda3/envs/vmoe_new/lib/python3.7/site-packages/jax/_src/dispatch.py", line 537, in backend_compile
    return backend.compile(built_c, compile_options=options)
RuntimeError: UNIMPLEMENTED: Requested AllToAll not implemented on GPU; replica_count: 1; partition_count: 8, group_mode: kCrossPartition, operand_count: 8; NCCL support: 1; first operand array element-type: BF16
```

**Comment by jpuigcerver** [comment]
Mmm. This seems to be a current limitation of JAX with a GPU backend.

I've tested the on a GPU, but only using 1 device, thus AllToAll is not used.

If you still want to use two GPU devices for taking advantage of data parallelism, and assuming that the model fits entirely on a single one of your GPUs, you could set `config.num_expert_partitions = 1`. This should prevent AllToAll from being needed, but you'll maybe have to reduce the batch size.

**Comment by Cascol-SCUT** [comment]
I have changed ```config.num_expert_partitions = config.model.encoder.moe.num_experts``` to ```config.num_expert_partitions = 1```.
However, it does not solve the above error. 
> Mmm. This seems to be a current limitation of JAX with a GPU backend.
> 
> I've tested the on a GPU, but only using 1 device, thus AllToAll is not used.
> 
> If you still want to use two GPU devices for taking advantage of data parallelism, and assuming that the model fits entirely on a single one of your GPUs, you could set `config.num_expert_partitions = 1`. This should prevent AllToAll from being needed, but you'll maybe have to reduce the batch size.

**Comment by BDHU** [comment]
@Cascol-SCUT I noticed your error message has `BF16` at the end. My understanding is `BF16` is only supported by TPU. Since you are using GPUs I think you should set the `bfloat16` to `False` in the config file to proceed.

**Comment by Cascol-SCUT** [comment]
Thanks for your reply! It solves the problem.

> @Cascol-SCUT @jpuigcerver I noticed the error message has `BF16` at the end. My understanding is `BF16` is only supported by TPU (or at least have limited support from CUDA or Jax). Since you are using GPUs I think you should set the `bfloat16` to `False` in the config file to proceed. Here's a quick look at [https://machine-learning-note.readthedocs.io/en/latest/blog/cheatsheets/Nvidia_GPU.html](https://machine-learning-note.readthedocs.io/en/latest/blog/cheatsheets/Nvidia_GPU.html#precision).
> 
> It seems like BF16 is only supported in Amphere GPUs. I don't think `config.num_expert_partitions` is the main problem but it's worth a try as well. Correct me if I'm wrong.
